package main

import (
	"net/http"
	"time"
	"strconv"
    "github.com/gin-gonic/gin"
	"slices"
)

type User struct {
	ID         uint   `gorm:"primaryKey" json:"id"` //adding the gorm primary id here since it is generated by gorm
	Name       string `json:"name"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	Age        int    `json:"age"`
	Gender     string `json:"gender"`
	Language   string `json:"language"`
	Address    string `json:"address"`
	Occupation string `json:"occupation"`
	CreatedAt  time.Time
	UpdatedAt  time.Time
}


func registerUser(c* gin.Context){             //register
	var newUser User
	if err := c.BindJSON(&newUser); err != nil {
		c.IndentedJSON(http.StatusBadRequest, gin.H{"message" : "Error binding json"})
		return
	}

	if err := saveUser(&newUser) ; err != nil {
		c.IndentedJSON(http.StatusInternalServerError, gin.H{"message": "Could not save the user"})
	    return
	}

	c.IndentedJSON(http.StatusCreated, gin.H{
		"message" : "User Created Successfully",
		"UserId" : newUser.ID,                   //gorm has automatically filled this field
	})
}

func getUsers(c* gin.Context){       // for debugging purposes      /users

	var users []User
	users, err := loadUsers()
    if err != nil {
		c.IndentedJSON(http.StatusInternalServerError, gin.H{"Message": "Could not read the file"})
		return
	}

	if len(users) == 0 {
		c.IndentedJSON(http.StatusOK, gin.H{
			"message": "No Users Registered",
		})
		return
	}

     c.IndentedJSON(http.StatusAccepted, &users)
}

func getUserByID(c *gin.Context) {           //getUser?id={userID}
	idParam := c.Query("id")
	if idParam == "" {
		c.IndentedJSON(http.StatusBadRequest, gin.H{"message": "Missing 'id' query parameter"})
		return
	}

	userID, err := strconv.ParseUint(idParam, 10, 64)
	if err != nil {
		c.IndentedJSON(http.StatusBadRequest, gin.H{"message": "Invalid 'id' format"})
		return
	}

	var user User
	if err := DB.First(&user, userID).Error; err != nil {
		c.IndentedJSON(http.StatusNotFound, gin.H{"message": "User not found"})
		return
	}

	c.JSON(http.StatusOK, user)
}


// Adding rider to a ride 

func addRiderToRide(c *gin.Context) {    //addRider?rideId={ride id}&riderId={rider id}
	
	rideIDParam := c.Query("rideId")
	riderIDParam := c.Query("riderId")


	if rideIDParam == "" || riderIDParam == "" {
		c.JSON(http.StatusBadRequest, gin.H{"message": "Missing rideId or riderId query parameter"})
		return
	}

	rideID, err1 := strconv.ParseUint(rideIDParam, 10, 64)
	riderID, err2 := strconv.ParseInt(riderIDParam, 10, 64)

	if err1 != nil || err2 != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "Invalid rideId or riderId format"})
		return
	}

	var ride Ride

	
	if err := DB.First(&ride, rideID).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"message": "Ride not found"})
		return
	}

	
	if slices.Contains(ride.RiderIDs, riderID) {
			c.JSON(http.StatusConflict, gin.H{"message": "Rider already added to this ride"})
			return
		}

	
	ride.RiderIDs = append(ride.RiderIDs, riderID)

	
	if err := DB.Save(&ride).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": "Failed to update ride with new rider"})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"message": "Rider successfully added to ride",
		"ride":    ride,
	})
}
